# 2021-01-04

apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    environment: sandbox
    app: nginx
spec:
  containers:
    - name: nginx
      image: nginx:1.14.2
      ports:
      - containerPort: 80